# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    # capture_screenshots(workspace: "SnapTesting.xcworkspace", scheme: "SnapTesting")
    run_tests(scheme: "SnapTesting")
    # sh "slather coverage --scheme SnapTesting --workspace SnapTesting.xcworkspace SnapTesting.xcodeproj"
  end
  lane :slathered do
    slather(
      scheme: "SnapTesting",
      workspace: "SnapTesting.xcworkspace",
      proj: "SnapTesting.xcodeproj",
      html: true,
      show: true
    )
  end

end
